=== WinLAFS/kthsedsav/PWS/HWs/HW3/JobServiceCompanyUDDI/src/java/employmentrecords/EmploymentRecord.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.kth.se/EmploymentRecord"
		xmlns="http://www.kth.se/EmploymentRecord" elementFormDefault="qualified">

 	<xs:element name="records">
 		<xs:complexType>
 			<xs:sequence>
 				<xs:element name="record" maxOccurs="unbounded">
 					<xs:complexType>
 						<xs:sequence>
 							<xs:element name="fromDate">
 								<xs:simpleType>
 									<xs:restriction base="xs:date">
 										<xs:minInclusive value="1920-01-01"></xs:minInclusive>
 										<xs:maxInclusive value="2010-02-10"></xs:maxInclusive>
 									</xs:restriction>
 								</xs:simpleType>
 							</xs:element>
 							<xs:element name="toDate">
 								<xs:simpleType>
 									<xs:restriction base="xs:date">
 										<xs:minInclusive value="1920-01-02"></xs:minInclusive>
 										<xs:maxInclusive value="2010-02-10"></xs:maxInclusive>
 									</xs:restriction>
 								</xs:simpleType>
 							</xs:element>
 							<xs:element name="position" type="xs:string"/>
 						</xs:sequence>
 						<xs:attribute name="companyName">
 							<xs:simpleType>
 								<xs:restriction base="xs:string">
 									<xs:minLength value="3"></xs:minLength>
 									<xs:maxLength value="16"></xs:maxLength>
 								</xs:restriction>
 							</xs:simpleType>
 						</xs:attribute>
 					</xs:complexType>
 				</xs:element>
 			</xs:sequence>
 		</xs:complexType>
 	</xs:element>
</xs:schema>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/HW2/JobServiceCompany/src/java/employmentrecords/EmploymentRecord.xml
<?xml version="1.0" encoding="UTF-8"?>

<records xmlns="http://www.kth.se/EmploymentRecord" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xsi:schemaLocation="http://www.kth.se/EmploymentRecord EmploymentRecord.xsd">
	<record companyName="IBM">
		<fromDate>2000-01-15</fromDate>
		<toDate>2004-04-10</toDate>
		<position>Developer</position>
	</record>
	<record companyName="Microsoft">
		<fromDate>2004-06-15</fromDate>
		<toDate>2008-03-20</toDate>
		<position>Developer</position>
	</record>
</records>
