=== WinLAFS/kthsedsav/trunk/PWS/HWs/HW3/JobServiceCompanyUDDI/src/java/jobservice/XMLs/profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.kth.se/profile" xmlns:tns="http://www.kth.se/profile" elementFormDefault="qualified">


<!-- types -->
<simpleType name="coolYear" >
	<restriction base="gYear">
		<minInclusive value="1940"></minInclusive>
		<maxInclusive value="2014"></maxInclusive>
	</restriction>
</simpleType>

<element name="profile">
	<complexType>
		<all>
			<element ref="tns:name"></element>
			<element ref="tns:surname"></element>
			<element ref="tns:birthDate"></element>
			<element ref="tns:degrees"></element>
			<element ref="tns:records"></element>
		</all>
	</complexType>
</element>
<element name="name">
	<simpleType>
		<restriction base="string">
			<pattern value="([A-Z]([a-z]*))"></pattern>
		</restriction>
	</simpleType>
</element>

<element name="surname">
	<simpleType>
		<restriction base="string">
			<pattern value="([A-Z]([a-z]*))"></pattern>
			<minLength value="2"></minLength>
		</restriction>
	</simpleType>
</element>

<element name="birthDate">
	<simpleType>
		<restriction base="date">
			<minInclusive value="1930-01-01"></minInclusive>
			<maxInclusive value="1990-01-01"></maxInclusive>
		</restriction>
	</simpleType>
</element>

<element name="university" type="string"></element>
<element name="startYear" type="tns:coolYear"></element>
<element name="endYear" type="tns:coolYear"></element>
<element name="subject" type="string"></element>
<element name="courseID" type="integer"></element>
<element name="gradeVal">
	<simpleType>
		<restriction base="integer">
			<minInclusive value="5"/>
	     	<maxInclusive value="10"/>
		</restriction>		
	</simpleType>
</element>




<!-- complex type definition -->
<element name="grades">
	<complexType>
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element ref="tns:grade"></element>
		</sequence>
	</complexType>
</element>

<element name="grade">
	<complexType>
		<sequence>
			<element ref="tns:gradeVal"></element>
		</sequence>
		<attribute name="courseID">
			<simpleType>
				<restriction base="integer">
					<maxInclusive value="666"></maxInclusive>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>
</element>

<element name="degree">
	<complexType>
		<all>
			<element ref="tns:university"></element>
			<element ref="tns:startYear"></element>
			<element ref="tns:endYear"></element>
			<element ref="tns:subject"></element>
			<element ref="tns:grades"></element>
			<element name="gpa" type="decimal" maxOccurs="1" minOccurs="0"></element>
		</all>
	<attribute name="title">
		<simpleType>
			<restriction base="string">
				<pattern value="MSc|Diploma|BSc"></pattern>
			</restriction>
		</simpleType>
	</attribute>
	</complexType>
</element>

<element name="degrees">
	<complexType>
		<sequence minOccurs="1" maxOccurs="unbounded">
			<element ref="tns:degree"></element>
		</sequence>
	</complexType>
</element>



<element name="records">
	<complexType>
		<sequence>
			<element name="record" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="fromDate">
							<simpleType>
								<restriction base="date">
									<minInclusive value="1920-01-01"></minInclusive>
									<maxInclusive value="2010-02-10"></maxInclusive>
								</restriction>
							</simpleType>
						</element>
						<element name="toDate">
							<simpleType>
								<restriction base="date">
									<minInclusive value="1920-01-02"></minInclusive>
									<maxInclusive value="2010-02-10"></maxInclusive>
								</restriction>
							</simpleType>
						</element>
						<element name="position" type="string" />
						<element name="site" type="string" />
					</sequence>
					<attribute name="companyName">
						<simpleType>
							<restriction base="string">
								<minLength value="3"></minLength>
								<maxLength value="16"></maxLength>
							</restriction>
						</simpleType>
					</attribute>
				</complexType>
			</element>
		</sequence>
	</complexType>
</element>
</schema>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/workspace/HW1/XMLs/allData.out.xml
<?xml version="1.0" encoding="UTF-8"?>
<profile xsi:schemaLocation="http://www.kth.se/profile profile.xsd"
	xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.kth.se/profile">
	<name>Vasilis</name>
	<surname>Melene</surname>
	<birthDate>1985-01-01</birthDate>
	<degrees>
		<degree title="MSc">
			<university>KTH</university>
			<startYear>2009</startYear>
			<endYear>2011</endYear>
			<subject>seds</subject>
			<grades>
				<grade courseID="1">
					<gradeVal>10</gradeVal>
				</grade>
				<grade courseID="2">
					<gradeVal>10</gradeVal>
				</grade>
				<grade courseID="3">
					<gradeVal>7</gradeVal>
				</grade>
			</grades>
			<gpa>9</gpa>
		</degree>
		<degree title="Diploma">
			<university>KTH</university>
			<startYear>2004</startYear>
			<endYear>2007</endYear>
			<subject>eve</subject>
			<grades>
				<grade courseID="11">
					<gradeVal>7</gradeVal>
				</grade>
				<grade courseID="22">
					<gradeVal>8</gradeVal>
				</grade>
			</grades>
			<gpa>7.5</gpa>
		</degree>
	</degrees>
	<records>
		<record>
			<fromDate>2000-01-15</fromDate>
			<toDate>2004-04-10</toDate>
			<position>Developer</position>
			<site>ibm.com</site>
		</record>
		<record>
			<fromDate>2004-06-15</fromDate>
			<toDate>2008-03-20</toDate>
			<position>Developer</position>
			<site>microsoft.com</site>
		</record>
	</records>
</profile>

=== WinLAFS/kthsedsav/PWS/HWs/workspace/HW1/XMLs/profile_SAX.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profile xmlns="http://www.kth.se/profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kth.se/profile profile.xsd">
<name>Vasilis</name>
<surname>Melene</surname>
<birthDate>1985-01-01</birthDate>
<degrees>
<degree>
<university>KTH</university>
<startYear>2009</startYear>
<endYear>2011</endYear>
<subject>seds</subject>
<grades>
<grade courseID="1">
<gradeVal>10</gradeVal>
</grade>
<grade courseID="2">
<gradeVal>10</gradeVal>
</grade>
</grades>
</degree>
</degrees>
<records>
<record companyName="IBM">
<fromDate>2000-01-15</fromDate>
<toDate>2004-04-10</toDate>
<position>Developer</position>
<site>IBM</site>
</record>
<record companyName="Microsoft">
<fromDate>2004-06-15</fromDate>
<toDate>2008-03-20</toDate>
<position>Developer</position>
<site>Microsoft</site>
</record>
</records>
</profile>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/workspace/HW1/XMLs/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:profile xmlns:tns="http://www.kth.se/profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kth.se/profile profile.xsd ">
  <tns:name>tns:name</tns:name>
  <tns:surname>tns:surname</tns:surname>
  <tns:birthDate>2001-01-01</tns:birthDate>
  <tns:degrees>
    <tns:degree tns:title="">
      <tns:university>tns:university</tns:university>
      <tns:startYear>2001</tn"all.xml"s:startYear>
      <tns:endYear>2001</tns:endYear>
      <tns:subject>tns:subject</tns:subject>
      <tns:grades>
        <tns:grade tns:courseID="0">
          <tns:gradeVal>0</tns:gradeVal>
        </tns:grade>
      </tns:grades>
    </tns:degree>
  </tns:degrees>
  <tns:records>
    <tns:record companyName="">
      <tns:fromDate>2001-01-01</tns:fromDate>
      <tns:toDate>2001-01-01</tns:toDate>
      <tns:position>tns:position</tns:position>
      <tns:site>tns:site</tns:site>
    </tns:record>
  </tns:records>
</tns:profile>
