=== WinLAFS/kthsedsav/trunk/PWS/HWs/HW3/JobServiceCompanyUDDI/src/java/university/Transcript.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.kth.se/Transcript"
	xmlns:tns="http://www.kth.se/Transcript" elementFormDefault="qualified">

	<!-- types -->
	<simpleType name="coolYear">
		<restriction base="gYear">
			<minInclusive value="1940"></minInclusive>
			<maxInclusive value="2014"></maxInclusive>
		</restriction>
	</simpleType>

	<!-- element definition -->
	<element name="university" type="string"></element>
	<element name="startYear" type="tns:coolYear"></element>
	<element name="endYear" type="tns:coolYear"></element>
	<element name="subject" type="string"></element>
	<element name="courseID" type="integer"></element>
	<element name="gradeVal">
		<simpleType>
			<restriction base="integer">
				<minInclusive value="5" />
				<maxInclusive value="10" />
			</restriction>
		</simpleType>
	</element>

	<!-- attribute definition -->



	<!-- complex type definition -->
	<element name="grades">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element ref="tns:grade"></element>
			</sequence>
		</complexType>
	</element>

	<element name="grade">
		<complexType>
			<sequence>
				<element ref="tns:gradeVal"></element>
			</sequence>
			<attribute name="courseID" type="integer"></attribute>
		</complexType>
	</element>

	<element name="degree">
		<complexType>
			<sequence>
				<element ref="tns:university"></element>
				<element ref="tns:startYear"></element>
				<element ref="tns:endYear"></element>
				<element ref="tns:subject"></element>
				<element ref="tns:grades"></element>
			</sequence>
			<attribute name="title">
				<simpleType>
					<restriction base="string">
						<pattern value="MSc|Diploma|BSc"></pattern>
					</restriction>
				</simpleType>
			</attribute>
		</complexType>
	</element>

	<element name="degrees">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<element ref="tns:degree"></element>
			</sequence>
		</complexType>
	</element>

</schema>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/workspace/HW1/XMLs/Transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:degrees xmlns:tns="http://www.kth.se/Transcript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kth.se/Transcript Transcript.xsd ">
  <tns:degree tns:title="MSc">
    <tns:university>KTH</tns:university>
    <tns:startYear>2009</tns:startYear>
    <tns:endYear>2011</tns:endYear>
    <tns:subject>seds</tns:subject>
    <tns:grades>
      <tns:grade tns:courseID="1">
        <tns:gradeVal>10</tns:gradeVal>
      </tns:grade>
      <tns:grade tns:courseID="2">
        <tns:gradeVal>10</tns:gradeVal>
      </tns:grade>
    </tns:grades>
  </tns:degree>
</tns:degrees>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/HW3/JobServiceCompanyUDDI/src/java/university/KTH/KTHStudent.xml
<degrees xmlns="http://www.kth.se/Transcript" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kth.se/Transcript Transcript.xsd ">
  <degree title="MSc">
    <university>KTH</university>
    <startYear>2009</startYear>
    <endYear>2011</endYear>
    <subject>SEDS</subject>
    <grades>
      <grade courseID="1">
        <gradeVal>10</gradeVal>
      </grade>
      <grade courseID="2">
        <gradeVal>10</gradeVal>
      </grade>
      <grade courseID="3">
        <gradeVal>8</gradeVal>
      </grade>
    </grades>
  </degree>
</degrees>
