=== WinLAFS/kthsedsav/PWS/HWs/HW2/JobServiceCompany/src/java/recruitercompany/jobadvertisment.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/jobadvertisment"
    xmlns:tns="http://xml.netbeans.org/schema/jobadvertisment"
    elementFormDefault="qualified">
    <xsd:element name="jobs">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="job">
                    <xsd:complexType>
                        <xsd:all>
                            <xsd:element name="title" type="xsd:string"/>
                            <xsd:element name="keywords" type="xsd:string"/>
                        </xsd:all>
                        <xsd:attribute name="id" type="xsd:string"/>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/HW2/JobServiceCompany/src/java/recruitercompany/jobadvertisment.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : jobadvertisment.xml
    Created on : February 14, 2010, 7:13 PM
    Author     : saibbot
    Description:
        Purpose of the document follows.
-->

<jobs  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://xml.netbeans.org/schema/jobadvertisment'
   xsi:schemaLocation='http://xml.netbeans.org/schema/jobadvertisment jobadvertisment.xsd'>
    <job id="1">
        <title>Software Engineer</title>
        <keywords>java, erlang</keywords>
    </job>
    <job id="2">
        <title>Software Developer</title>
        <keywords>c, c++, uml</keywords>
    </job>
    <job id="3">
        <title>Web Developer</title>
        <keywords>CSS, XML, PHP, JQuery</keywords>
    </job>
    <job id="4">
        <title>Application Support</title>
        <keywords>Oracle, Python, C++</keywords>
    </job>
</jobs>
