=== WinLAFS/kthsedsav/trunk/PWS/HWs/workspace/HW1/XMLs/CompaniesInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.kth.se/CompaniesInfo"
		xmlns="http://www.kth.se/CompaniesInfo" elementFormDefault="qualified">

<!-- definition of simple elements -->
<xs:element name="country" type="xs:string"/>
<xs:element name="city" type="xs:string"/>
<xs:element name="index">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>
<xs:element name="line1" type="xs:string" />
<xs:element name="line2" type="xs:string" />

<xs:element name="numberOfEmployees">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="foundedYear">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1100"/>
			<xs:maxInclusive value="2010"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>
<xs:element name="CEO" type="xs:string"/>
<xs:element name="site" type="xs:string"/>

<!-- definition of complex elements -->
<xs:complexType name="address">
	<xs:sequence>
		<xs:element ref="country"/>
		<xs:element ref="city"/>
		<xs:element ref="index"/>
		<xs:element ref="line1"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="addressExt">
	<xs:complexType>
		<xs:complexContent>
			<xs:extension base="address">
				<xs:sequence>
					<xs:element ref="line2"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:element>

<xs:element name="company">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="addressExt"/>
			<xs:element ref="numberOfEmployees"/>
			<xs:element ref="foundedYear"/>
			<xs:element ref="CEO"/>
			<xs:element ref="site"/>
		</xs:sequence>
		<xs:attribute name="companyName" type="xs:string" />
	</xs:complexType>
</xs:element>

<xs:element name="companies">
	<xs:complexType>
		<xs:sequence>
			<xs:element ref="company" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== WinLAFS/kthsedsav/trunk/PWS/HWs/workspace/HW1/XMLs/CompaniesInfo.xml
<?xml version="1.0" encoding="UTF-8"?>

<companies xmlns="http://www.kth.se/CompaniesInfo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		 xsi:schemaLocation="http://www.kth.se/CompaniesInfo CompaniesInfo.xsd">
	<company companyName="IBM">
		<addressExt>
			<country>Sweden</country>
			<city>Stockholm</city>
			<index>164 92</index>
			<line1></line1>
			<line2></line2>
		</addressExt>
		<numberOfEmployees>400000</numberOfEmployees>
		<foundedYear>1896</foundedYear>
		<CEO>Samuel J Palmisano</CEO>
		<site>ibm.com</site>
	</company>
	
</companies>
